name: Git Sync Action
author: Wei He <github@weispot.com>
description: 🔃 Sync between two independent repositories
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  source_repo:
    description: GitHub repo slug or full clone url
    required: true
  destination_repo:
    description: GitHub repo slug or full clone url
    required: true
  username:
    description: User of committer
    required: true
  user_password:
    description: Password of user that's doing the commit
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.destination_repo }}
    - ${{ inputs.username }}
    - ${{ inputs.user_password }}